#!/bin/bash


aptitude update
aptitude install chef -y

mkdir /etc/chef

# set the ec2 ohai hints so ohai knows it's in a ec2, VPCs mess it up.
mkdir -p /etc/chef/ohai/hints
touch /etc/chef/ohai/hints/ec2.json

cat >> /etc/chef/client.rb << EOF
log_level               :info
log_location            STDOUT
chef_server_url         'https://{chef_url}/organizations/{org}'
validation_key          '/etc/chef/chef-validator.pem'
validation_client_name  '{org}-validator'
EOF

# Write first boot json
echo "{{\"run_list\": [\"role[{role}]\"]}}" > /etc/chef/firstrun.json
echo '{encrypted_data_bag}' > /etc/chef/encrypted_data_bag_secret

# Write Validation key to server
echo '{validation_key}' > /etc/chef/chef-validator.pem

chef-client -j /etc/chef/firstrun.json -E {environment}
